_target_: dl4bi.meta_learning.TNPKR
num_blks: 6
num_reps: 1
embed_x:
  _target_: dl4bi.embed.IDEmbedding
  num_ids: 18
  num_features: 32
embed_all:
  _target_: dl4bi.mlp.MLP
  dims: [256, 128, 64]
  act_fn:
    _target_: jax.nn.gelu
    _partial_: true
blk:
  _target_: dl4bi.transformer.KRBlock
  attn:
    _target_: dl4bi.attention.MultiHeadAttention
    num_heads: 4
    attn:
      _target_: dl4bi.attention.Attention
    proj_qs:
      _target_: dl4bi.mlp.MLP
      dims: [128]
    proj_ks:
      _target_: dl4bi.mlp.MLP
      dims: [128]
    proj_vs:
      _target_: dl4bi.mlp.MLP
      dims: [128]
  ffn:
    _target_: dl4bi.mlp.MLP
    dims: [256, 64]
    act_fn:
      _target_: jax.nn.gelu
      _partial_: true
head:
  _target_: dl4bi.mlp.MLP
  dims: [256, 64, 2]
  act_fn:
    _target_: jax.nn.gelu
    _partial_: true
