cls: DeepRV
kwargs:
  cond_stack_fn:
    func: cond_as_feats
  decoder:
    cls: FixedLocationTransfomer
    kwargs:
      num_blks: 3
      blk:
        cls: TransformerEncoderBlock
        kwargs:
          pre_norm: True
          attn:
            cls: MultiHeadAttention
            kwargs:
              num_heads: 2
              attn:
                cls: RBFNetworkBiasedScanAttention
                kwargs:
                  qs_chunk_size: 1024
                  ks_chunk_size: 1024
                  num_basis: 2
          ffn:
            cls: MLP
            kwargs:
              dims: [128, 64]

