spatial_prior:
  func: matern_5_2
priors: # Priors for training DeepRV or for inference
  var:
    numpyro_dist: Dirichlet # Replacement for Delta distribution which always outputs '1'
    kwargs:
      concentration: [1.0]
  ls:
    numpyro_dist: Uniform
    kwargs:
      low: 0.01
      high: 0.99