model: # Inference model function to choose from inference_models/inference_models.py
  func: noisy_spatial_model
spatial_prior:
  func: rbf
# priors names and args must be compat with Numpyro distributions
priors: # Priors for inference model data generation
  sigma:
    numpyro_dist: Delta
    kwargs:
      v: 0.2
  var:
    numpyro_dist: Delta
    kwargs:
      v: 1.0
  ls:
    numpyro_dist: Uniform
    kwargs:
      low: 0.0
      high: 1.0
  period: # Would only be used if training prior is Periodic
    numpyro_dist: HalfNormal
surrogate_model: True # Whether to use a surrogate model or and actual GP sampling
num_obs_locations: null # Can be used to randomly select partial number of locations for inference
