defaults:
  - _self_ # use default global values below
  - model: mdn
seed: 42
wandb: False
project: SBI
train_num_steps: 10000
valid_num_steps: 100
valid_interval: 250
data:
  batch_size: 32
  simulator: theta_cubed
  theta:
    min: -3.0
    max: 3.0
  noise: 0.5
lr_peak: 1.0e-3
lr_pct_warmup: 0.01
clip_max_norm: 3.0
save_ckpt: False
