defaults:
  - _self_ # use default global values below
  - data: 1d
  - infer: 1d
  - model: 1d/tnp_kr
wandb: True
seed: 42
infer_seed: 42
infer_model: spatial
infer_compare: False
project: Hierarchical Bayes
train_num_steps: 1000000
valid_num_steps: 5000
valid_interval: 10000
plot_interval: 100000
lr_peak: 1.0e-3
lr_pct_warmup: 0.0
clip_max_norm: 3.0
