_target_: sps.gp.GP
kernel:
  _target_: sps.kernels.matern_1_2
  _partial_: true
var:
  _target_: sps.priors.Prior
  dist: normal
  kwargs:
    mu: 1.0
    sigma: 0.1
ls:
  _target_: sps.priors.Prior
  dist: normal
  kwargs:
    mu: 1.0
    sigma: 0.15
