cls: GP
kwargs: 
  kernel:
    func: periodic
  var:
    cls: Prior
    kwargs:
      dist: fixed
      kwargs:
        value: 1.0
  ls:
    cls: Prior
    kwargs:
      dist: beta
      kwargs:
        a: 3.0
        b: 7.0
  period:
    cls: Prior
    kwargs:
      dist: uniform
      kwargs:
        minval: 1.57 # ~4 cycles on unit interval (2π / 4)
        maxval: 6.28 # ~1 cycle on unit interval (2π / 1)
