cls: CNP
kwargs:
  enc_det:
    cls: MLP
    kwargs:
      dims: [128, 128, 128, 128, 128, 128]
  dec:
    cls: MLP
    kwargs:
      dims: [128, 128, 128, 128, 6]
  output_fn:
    func: 'lambda x: diagonal_mvn(x, min_std=0.05)'
