# https://github.com/YannDubs/Neural-Process-Family/blob/master/jupyter/reproducibility/ConvCNP.ipynb
cls: ConvCNP
kwargs:
  s_lower: [-2.5, -2.5] # add 0.5 padding on each size as in ConvCNP impl
  s_upper: [2.5, 2.5]
  points_per_unit: 16
  enc:
    cls: ConvDeepSet
    kwargs:
      d_out: 128
  conv_net:
    cls: ConvCNPNet
    kwargs:
      r_dim: 128
      kernel: [9, 9]
      num_blks: 12
  dec:
    cls: ConvDeepSet
    kwargs:
      d_out: 128
  head:
    cls: MLP
    kwargs:
      dims: [128, 128, 128, 128, 6]
  output_fn:
    func: 'lambda x: diagonal_mvn(x, min_std=0.05)'
