cls: GP
kwargs: 
  kernel:
    func: periodic
  var:
    cls: Prior
    kwargs:
      dist: fixed
      kwargs:
        value: 1.0
  ls:
    cls: Prior
    kwargs:
      dist: beta
      kwargs:
        a: 3.0
        b: 7.0
  period:
    cls: Prior
    kwargs:
      dist: uniform
      kwargs:
        minval: 0.5 # 8 cycles on [-2, 2]
        maxval: 2 # 2 cycles on [-2, 2]
