defaults:
  - _self_ # use default global values below
  - data: spatial_64x64
  - sim: priors
  - model: tnp_kr_scan
seed: 42
wandb: True
project: SIR
train_num_steps: 100000
valid_num_steps: 1000
valid_interval: 10000
plot_interval: 100000
evaluate_only: False
optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 3.0
    - _target_: optax.add_decayed_weights
      weight_decay: 1.0e-2
    - _target_: optax.yogi
      learning_rate:
        _target_: optax.cosine_decay_schedule
        init_value: 1.0e-3
        decay_steps: ${train_num_steps}
        alpha: 1.0e-4
