cls: BNP
kwargs:
  num_samples: 4 # as specified in paper
  enc_det:
    cls: MLP
    kwargs:
      dims: [128, 128, 128, 128, 128, 128]
  dec_hid:
    cls: MLP
    kwargs:
      dims: [128]
  dec_boot:
    cls: MLP
    kwargs:
      dims: [128]
  dec_dist:
    cls: MLP
    kwargs:
      dims: [128, 128, 128, 2]
  output_fn:
    func: 'lambda x: diagonal_mvn(x, min_std=0.05)'
