cls: BANP
kwargs:
  num_samples: 4 # as specified in paper
  embed_s:
    cls: MLP
    kwargs:
      dims: [512, 128]
  enc_det:
    cls: MLP
    kwargs:
      dims: [512, 256, 128]
  self_attn_det:
    cls: MultiHeadAttention
    kwargs:
      num_heads: 8
      proj_qs:
        cls: MLP
        kwargs:
          dims: [128]
      proj_ks:
        cls: MLP
        kwargs:
          dims: [128]
      proj_vs:
        cls: MLP
        kwargs:
          dims: [128]
      proj_out:
        cls: MLP
        kwargs:
          dims: [128]
  cross_attn:
    cls: MultiHeadAttention
    kwargs:
      num_heads: 8
      proj_qs:
        cls: MLP
        kwargs:
          dims: [128]
      proj_ks:
        cls: MLP
        kwargs:
          dims: [128]
      proj_vs:
        cls: MLP
        kwargs:
          dims: [128]
      proj_out:
        cls: MLP
        kwargs:
          dims: [128]
  dec_hid:
    cls: MLP
    kwargs:
      dims: [128]
  dec_boot:
    cls: MLP
    kwargs:
      dims: [128]
  dec_dist:
    cls: MLP
    kwargs:
      dims: [512, 128, 128, 128, 2]
