_target_: dl4bi.meta_learning.BSATNP
num_blks: 6
num_reps: 1
embed_x:
  _target_: dl4bi.embed.IDEmbedding
  num_ids: 24
  num_features: 16
  channel: 0
embed_all:
  _target_: dl4bi.mlp.MLP
  dims: [512, 256, 128, 64]
  act_fn:
    _target_: jax.nn.gelu
    _partial_: true
blk:
  _target_: dl4bi.transformer.KRBlock
  attn:
    _target_: dl4bi.attention.MultiHeadAttention
    attn:
      _target_: dl4bi.attention.BiasedScanAttention
      bias:
        _target_: builtins.dict
        s:
          _target_: dl4bi.bias.Bias.build_rbf_network_bias
          num_heads: 4
          num_basis: 5
        t:
          _target_: dl4bi.bias.Bias.build_rbf_network_bias
          num_heads: 4
          num_basis: 3
    proj_qs:
      _target_: dl4bi.mlp.MLP
      dims: [128]
    proj_ks:
      _target_: dl4bi.mlp.MLP
      dims: [128]
    proj_vs:
      _target_: dl4bi.mlp.MLP
      dims: [128]
    proj_out:
      _target_: dl4bi.mlp.MLP
      dims: [64]
  ffn:
    _target_: dl4bi.mlp.MLP
    dims: [256, 64]
    act_fn:
      _target_: jax.nn.gelu
      _partial_: true
head:
  _target_: dl4bi.mlp.MLP
  dims: [256, 64, 1]
  act_fn:
    _target_: jax.nn.gelu
    _partial_: true
output_fn:
  _target_: dl4bi.core.model_output.PoissonOutput.from_activations
  _partial_: true
