defaults:
  - _self_ # use default global values below
  - data: map_data
  - model: auto_deep_RV
  - inference_model: poisson
exp_name: null
seed: 42
wandb: True
project: deep_RV
log_scale_plots: True
approx_infer_guide: null
mcmc:
  num_warmup: 4000
  num_samples: 10000
  num_chains: 4
train_num_steps: 100000
valid_num_steps: 5000
valid_interval: 25000
plot_interval: 100000
cosine_annealing: True
lr_peak: 1.0e-2
lr_pct_warmup: 0.01
clip_max_norm: 3.0
emprical_bayes_samples: 100