defaults:
  - _self_ # use default global values below
  - model: tnp_kr_scan
seed: 42
wandb: True
project: MNIST
train_num_steps: 100000
valid_num_steps: null # exhaust valid dataloader
valid_interval: 10000
plot_interval: 100000
lr_peak: 5.0e-4
lr_pct_warmup: 0.0
clip_max_norm: 1.0
