defaults:
  - _self_ # use default global values below
  - model: b_tnp
seed: 42
wandb: True
project: Outbreaks
train_num_steps: 100000
valid_num_steps: 1000
valid_interval: 25000
plot_interval: 5000
batch_size: 16
lr_peak: 1.0e-3
lr_pct_warmup: 0.0
clip_max_norm: 3.0
