_target_: dl4bi.meta_learning.TETNP
encoder:
  _target_: dl4bi.transformer.TEEncoder
  num_blks: 5
  blk:
    _target_: dl4bi.transformer.TEBlock
    attn:
      _target_: dl4bi.attention.TEMultiHeadAttention
      num_heads: 8
      proj_qs:
        _target_: dl4bi.mlp.MLP
        dims: [128]
      proj_ks:
        _target_: dl4bi.mlp.MLP
        dims: [128]
      proj_vs:
        _target_: dl4bi.mlp.MLP
        dims: [128]
      proj_out:
        _target_: dl4bi.mlp.MLP
        dims: [128]
      kernel:
        _target_: dl4bi.mlp.MLP
        dims: [128, 128, 8]
    ffn:
      _target_: dl4bi.mlp.MLP
      dims: [128, 128]
decoder:
  _target_: dl4bi.mlp.MLP
  dims: [128, 128, 2]
embed_f:
  _target_: dl4bi.mlp.MLP
  dims: [128, 128]
output_fn:
  _target_: dl4bi.model_output.DiagonalMVNOutput.from_activations
  _partial_: true
