cls: SPTx
kwargs:
  embed_s_f:
    cls: MLP
    kwargs:
      dims: [256, 128, 64, 64]
  dec:
    cls: KRStack
    kwargs:
      num_blks: 3
      num_reps: 2
      resid_blk: True
      blk:
        cls: KRBlock
        kwargs:
          attn:
            cls: MultiheadAttention
  head:
    cls: MLP
    kwargs:
      dims: [128, 6]
