# https://github.com/YannDubs/Neural-Process-Family/blob/master/jupyter/reproducibility/ConvCNP.ipynb
cls: ConvCNP
kwargs:
  grid:
  - start: -2.5
    stop: 2.5
    num: 16
  - start: -2.5
    stop: 2.5
    num: 16
  enc:
    cls: ConvDeepSet
    kwargs:
      d_out: 128
  conv_net:
    cls: ConvCNPNet
    kwargs:
      r_dim: 128
      kernel: [7, 7]
      num_blks: 5
  dec:
    cls: ConvDeepSet
    kwargs:
      d_out: 128
  head:
    cls: MLP
    kwargs:
      dims: [128, 128, 128, 128, 6]
