cls: TNPD
kwargs:
  embed_s_f:
    cls: MLP
    kwargs:
      dims: [64, 64, 64, 64]
  enc:
    cls: TransformerEncoder
    kwargs:
      blk:
        cls: TransformerEncoderBlock
        kwargs:
          pre_norm: False
  head:
    cls: MLP
    kwargs:
      dims: [128, 6]
