cls: TNPD
kwargs:
  embed_s_f:
    cls: MLP
    kwargs:
      dims: [64, 64, 64, 64]
  enc:
    cls: TransformerEncoder
    kwargs:
      num_blks: 6
      blk:
        cls: TransformerEncoderBlock
        kwargs:
          attn:
            cls: MultiheadAttention
            kwargs:
              num_heads: 4
              p_dropout: 0.0
          ffn:
            cls: MLP
            kwargs:
              dims: [128, 64]
          p_dropout: 0.0
  head:
    cls: MLP
    kwargs:
      dims: [128, 6]
