defaults:
  - _self_ # use default global values below
  - model: tnp_kr_scan
seed: 42
wandb: True
project: ERA5
train_num_steps: 100000
valid_num_steps: 1000 # exhaust valid dataloader
valid_interval: 5000
plot_interval: 50000
data:
  batch_size: 16
  num_ctx_min_per_t: 12  # ~5% of 225 = 15 * 15
  num_ctx_max_per_t: 56  # ~25% of 225 = 15 * 15
  num_test: 225  # 225 = 15 * 15 = predicted frame
  train_region: central_europe
  valid_region: northern_europe
  test_region: western_europe
  num_batches_per_subset: 50
optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 1.0
    - _target_: optax.adamw
      learning_rate:
        _target_: optax.cosine_decay_schedule
        init_value: 1.0e-3
        decay_steps: ${train_num_steps}
        alpha: 1.0e-4
      b1: 0.9
      b2: 0.999
      weight_decay: 1.0e-4
