defaults:
  - _self_ # use default global values below
  - model: bsa_tnp
  - data: full
seed: 42
wandb: True
project: ERA5
train_num_steps: 100000
valid_num_steps: 5000 # exhaust valid dataloader
valid_interval: 5000
plot_interval: 100000
optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 0.5
    - _target_: optax.adamw
      learning_rate: 5.0e-4
      b1: 0.9
      b2: 0.999
      weight_decay: 1.0e-4
