cls: TNPKR
kwargs:
  num_blks: 6
  num_reps: 1
  embed_all:
    cls: MLP
    kwargs:
      dims: [256, 128, 64]
      act_fn: gelu
  dist:
    func: l2_dist
  bias:
    cls: RBFNetworkBias
    kwargs:
      num_basis: 5
      num_heads: 4
  blk:
    cls: KRBlock
    kwargs:
      attn:
        cls: MultiHeadAttention
        kwargs:
          num_heads: 4
          attn:
            cls: Attention
          proj_qs:
            cls: MLP
            kwargs:
              dims: [128]
          proj_ks:
            cls: MLP
            kwargs:
              dims: [128]
          proj_vs:
            cls: MLP
            kwargs:
              dims: [128, 64]
    ffn:
      cls: MLP
      kwargs:
        dims: [256, 64]
        act_fn: gelu
  head:
    cls: MLP
    kwargs:
      dims: [256, 64, 2]
      act_fn: gelu
