cls: PriorCVAE
kwargs:
  cond_stack_fn:
    func: append_cond_to_locs
  encoder:
    cls: MLP
    kwargs:
      dims: [128, 128]
  decoder:
    cls: MLP
    kwargs:
      dims: [128, 128]
  z_dim: 128
