cls: GP
kwargs: 
  kernel:
    func: matern_1_2
  var:
    cls: Prior
    kwargs:
      dist: normal
      kwargs:
        mu: 1.02
        sigma: 0.1
  ls:
    cls: Prior
    kwargs:
      dist: normal
      kwargs:
        mu: 0.97
        sigma: 0.2
