defaults:
  - _self_ # use default global values below
  - model: tnp_kr_scan
  - kernel: matern_1_2
  - data: 30x50
  - test: sim
seed: 42
wandb: True
project: Heaton
train_num_steps: 50000
valid_num_steps: 100
valid_interval: 5000
plot_interval: 50000
finetune_num_steps: 1000
finetune_on_real: True
lr_finetune: 2.0e-4
optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 1.0
    - _target_: optax.adamw
      learning_rate:
        _target_: optax.cosine_decay_schedule
        init_value: 2.0e-3
        decay_steps: ${train_num_steps}
        alpha: 2.0e-5
      b1: 0.9
      b2: 0.999
      weight_decay: 1.0e-4
