_target_: ANP
embed_s:
  _target_: dl4bi.mlp.MLP
  dims: [128, 128]
enc_det:
  _target_: dl4bi.mlp.MLP
  dims: [128, 128, 128]
enc_lat:
  _target_: dl4bi.mlp.MLP
  dims: [128, 128, 128]
self_attn_det:
  _target_: dl4bi.attention.MultiHeadAttention
  num_heads: 8
  proj_qs:
    _target_: dl4bi.mlp.MLP
    dims: [128]
  proj_ks:
    _target_: dl4bi.mlp.MLP
    dims: [128]
  proj_vs:
    _target_: dl4bi.mlp.MLP
    dims: [128]
  proj_out:
    _target_: dl4bi.mlp.MLP
    dims: [128]
self_attn_lat:
  _target_: dl4bi.attention.MultiHeadAttention
  num_heads: 8
  proj_qs:
    _target_: dl4bi.mlp.MLP
    dims: [128]
  proj_ks:
    _target_: dl4bi.mlp.MLP
    dims: [128]
  proj_vs:
    _target_: dl4bi.mlp.MLP
    dims: [128]
  proj_out:
    _target_: dl4bi.mlp.MLP
    dims: [128]
z_dist:
  _target_: dl4bi.mlp.MLP
  dims: [128, 256]
cross_attn:
  _target_: dl4bi.attention.MultiHeadAttention
  num_heads: 8
  proj_qs:
    _target_: dl4bi.mlp.MLP
    dims: [128]
  proj_ks:
    _target_: dl4bi.mlp.MLP
    dims: [128]
  proj_vs:
    _target_: dl4bi.mlp.MLP
    dims: [128]
  proj_out:
    _target_: dl4bi.mlp.MLP
    dims: [128]
dec:
  _target_: dl4bi.mlp.MLP
  dims: [128, 128, 128, 128, 6]
n_z: 1
