# https://github.com/YannDubs/Neural-Process-Family/blob/master/jupyter/reproducibility/ConvCNP.ipynb
_target_: dl4bi.meta_learning.ConvCNP
s_lower: [-2.5, -2.5] # add 0.5 padding on each size as in ConvCNP impl
s_upper: [2.5, 2.5]
points_per_unit: 16
enc:
  _target_: dl4bi.conv.ConvDeepSet
  d_out: 128
conv_net:
  _target_: dl4bi.conv.ConvCNPNet
  r_dim: 128
  kernel: [9, 9]
  num_blks: 5
dec:
  _target_: dl4bi.conv.ConvDeepSet
  d_out: 128
head:
  _target_: dl4bi.mlp.MLP
  dims: [128, 128, 128, 6]
