_target_: dl4bi.meta_learning.NP
enc_det:
  _target_: dl4bi.mlp.MLP
  dims: [128, 128, 128, 128, 128, 128]
enc_lat:
  _target_: dl4bi.mlp.MLP
  dims: [128, 128, 128]
z_dist:
  _target_: dl4bi.mlp.MLP
  dims: [128, 256]
dec:
  _target_: dl4bi.mlp.MLP
  dims: [128, 128, 128, 128, 6]
n_z: 1
