cls: DKR
kwargs:
  num_layers: 3
  num_repeats: 2
  embed_s:
    cls: LearnableEmbedding
    kwargs:
      post_process:
        cls: MLP
        kwargs:
          dims: [64, 64, 64, 64]
          act_fn: elu
  embed_s_f:
    cls: MLP
    kwargs:
      dims: [64]
      act_fn: elu
  attn:
    cls: MultiheadAttention
    kwargs:
      proj_out:
        cls: MLP
        kwargs:
          dims: [64, 64]
          act_fn: elu
  head:
    cls: MLP
    kwargs:
      dims: [64, 64, 2]
      act_fn: elu
