cls: TNPKR
kwargs:
  min_std: 0.05
  embed_s_f:
    cls: MLP
    kwargs:
      dims: [256, 64]
  dec:
    cls: KRStack
    kwargs:
      blk:
        cls: KRBlock
        kwargs:
          attn:
            cls: MultiHeadAttention
  head:
    cls: MLP
    kwargs:
      dims: [128, 2]
