cls: NP
kwargs:
  enc_det:
    cls: MLP
    kwargs:
      dims: [128, 128, 128, 128, 128, 128]
  enc_lat:
    cls: MLP
    kwargs:
      dims: [128, 128, 128]
  z_dist:
    cls: MLP
    kwargs:
      dims: [128, 256]
  dec:
    cls: MLP
    kwargs:
      dims: [128, 128, 128, 128, 2]
  n_z: 1
