_target_: dl4bi.meta_learning.sgnp.SGNP
s_sim:
  _target_: dl4bi.sim.l2_dist
  _partial_: true
s_bias:
  _target_: dl4bi.bias.Bias.build_rbf_network_bias
  num_basis: 5
  num_heads: 4
blk:
  _target_: dl4bi.gnn.GraphAttentionBlock
  attn:
    _target_: dl4bi.attention.MultiHeadGraphAttention
    proj_qks:
      _target_: dl4bi.mlp.MLP
      dims: [128]
    proj_vs:
      _target_: dl4bi.mlp.MLP
      dims: [128]
    proj_out:
      _target_: dl4bi.mlp.MLP
      dims: [64]
head:
  _target_: dl4bi.mlp.MLP
  dims: [256, 64, 3]
  act_fn:
    _target_: jax.nn.gelu
    _partial_: true
output_fn:
  _target_: dl4bi.core.model_output.MultinomialOutput.from_activations
  _partial_: true
