cls: DKR
kwargs:
  depth: 5
  embed_s:
    cls: LearnableEmbedding
    kwargs:
      map:
        cls: GaussianFourierEmbedding
        kwargs:
          embed_dim: 8
          var: 4.0
      post_process:
        cls: MLP
        kwargs:
          dims: [64, 64]
          act_fn: elu
  embed_s_f:
    cls: MLP
    kwargs:
      dims: [64]
      act_fn: elu
  # attn:
  #   cls: MultiheadAttention
  #   kwargs:
  #     proj_out:
  #       cls: MLP
  #       kwargs:
  #         dims: [128, 64]
  #         act_fn: elu
  head:
    cls: MLP
    kwargs:
      dims: [64, 64, 2]
      act_fn: elu
