_target_: dl4bi.meta_learning.ScanTNPKR
num_blks: 6
num_reps: 1
embed_s:
  _target_: dl4bi.meta_learning.utils.x_to_none
  _partial_: true
embed_all:
  _target_: dl4bi.mlp.MLP
  dims: [256, 128, 64]
  act_fn:
    _target_: jax.nn.gelu
    _partial_: true
blk:
  _target_: dl4bi.transformer.KRBlock
  attn:
    _target_: dl4bi.attention.MultiHeadAttention
    num_heads: 4
    attn:
      _target_: dl4bi.attention.BiasedScanAttention
      s_bias:
        _target_: dl4bi.bias.Bias.build_rbf_network_bias
        num_heads: 4
        num_basis: 5
    proj_qs:
      _target_: dl4bi.mlp.MLP
      dims: [128]
    proj_ks:
      _target_: dl4bi.mlp.MLP
      dims: [128]
    proj_vs:
      _target_: dl4bi.mlp.MLP
      dims: [128]
  ffn:
    _target_: dl4bi.mlp.MLP
    dims: [256, 64]
    act_fn:
      _target_: jax.nn.gelu
      _partial_: true
head:
  _target_: dl4bi.mlp.MLP
  dims: [256, 64, 2]
  act_fn:
    _target_: jax.nn.gelu
    _partial_: true
