_target_: dl4bi.regression.DNonLinear
num_output: 30
seasonal_lags: [7]
lag_fn:
  _target_: dl4bi.core.utils.causal_moving_average
  _partial_: true
num_layers: 2
act_fn:
  _target_: jax.nn.gelu
  _partial_: true
output_fn:
  _target_: dl4bi.core.model_output.PoissonOutput.from_activations
  _partial_: true
