defaults:
  - _self_ # use default global values below
  - model: tnp_kr
seed: 42
wandb: True
project: MLBI - Baseball
train_num_steps: 1000
valid_num_steps: 250
valid_interval: 250
lr_peak: 1.0e-3
clip_max_norm: 3.0
data:
  batch_size: 32
  num_ctx_min: 3
  num_ctx_max: 12
  num_test: 18
  test_includes_ctx: True
infer:
  num_warmup: 1000
  num_samples: 1000
  num_chains: 1
