defaults:
  - _self_ # use default global values below
  - model: b_tnp
seed: 42
wandb: True
project: Population Genetics
train_num_steps: 500000
valid_num_steps: 5000
valid_interval: 50000
plot_interval: 100000
batch_size: 16
optimizer:
  _target_: optax.chain
  _args_:
    - _target_: optax.clip_by_global_norm
      max_norm: 3.0
    - _target_: optax.yogi
      learning_rate:
        _target_: optax.cosine_decay_schedule
        init_value: 1.0e-3
        decay_steps: ${train_num_steps}
        alpha: 1.0e-4
