defaults:
  - _self_ # use default global values below
  - data: sim
  - model: tnp_kr_fast_rff
seed: 42
wandb: True
project: Heaton
train_num_steps:
 - 3000
 - 3000
 - 3000
 - 1000
 - 500
valid_num_steps: null # exhaust valid_dataloader
valid_interval: 100
lr_peak: 2.0e-3
lr_pct_warmup: 0.2
clip_max_norm: 3.0
