defaults:
  - _self_ # use default global values below
  - data: sim
  - model: tnp_kr_fast
seed: 42
wandb: True
project: Heaton
train_num_steps: 100000
valid_num_steps: null # exhaust valid_dataloader
valid_interval: 1000
plot_interval: 25000
lr_peak: 3.0e-3
lr_pct_warmup: 0.0
clip_max_norm: 3.0
