defaults:
  - _self_ # use default global values below
  - model: tnp_kr
seed: 42
wandb: True
project: Population Genetics
train_num_steps: 500000
valid_num_steps: 5000
valid_interval: 50000
plot_interval: 100000
batch_size: 16
lr_peak: 1.0e-3
lr_pct_warmup: 0.0
clip_max_norm: 3.0
