data:
  grid:
    - start: 0.0
      stop: 1.0
      num: 128
  num_test: 16
  period: 0.2
  loader:
    obs_noise: 0.1
    min_p: 0.05
    max_p: 0.50
    batch_size: 64

infer:
  num_warmup: 500
  num_samples: 1000

train:
  num_batches: 5000

shared:
  pe_dim: 16
  embed_dim: 64

model:
  cls: HFTx
  kwargs:
    embed_s:
      cls: LearnableEmbedding
      kwargs:
        map:
          # func: 'lambda x: x' # only learned embeddings
          cls: GaussianFourierEmbedding
          kwargs:
            embed_dim: ${shared.pe_dim}
            input_dim: 1
            var: 10.0
        post_process:
          cls: MLP
          kwargs:
            dims: ${eval:'[${shared.embed_dim}]*2'}
            p_dropout: 0.2
    embed_s_f:
      cls: MLP
      kwargs:
        dims: ${eval:'[${shared.embed_dim}]*1'}
        p_dropout: 0.0
    enc:
      cls: TransformerEncoder
      kwargs:
        attention:
          cls: MultiheadFastSoftmaxAttention
          # cls: MultiheadAttention
          kwargs:
            p_dropout: 0.0
        num_blks: 3
        p_dropout: 0.2
    cross_attn:
      cls: MultiheadFastSoftmaxAttention
      # cls: MultiheadAttention
      kwargs:
        p_dropout: 0.0
    dec:
      cls: MLP
      kwargs:
        dims: ${eval:'[${shared.embed_dim}]*3+[2]'}
        p_dropout: 0.0
