data:
  grid:
    - start: -2.0
      stop: 2.0
      num: 128
  num_test: 16
  period: 0.2
  loader:
    obs_noise: 0.0
    min_p: 0.05
    max_p: 0.50
    batch_size: 16

infer:
  num_warmup: 500
  num_samples: 1000

train:
  ckpt_path: ckpts/sptx
  num_batches: 200000
  num_warmup: 10
  learning_rate:
    peak: 1.0e-3
    num_cycles: 1
  redraw_random_features_every_n: 100001

shared:
  pe_dim: 16
  embed_dim: 64

model:
  cls: SPTx
  kwargs:
    embed_s:
      cls: LearnableEmbedding
      kwargs:
        map:
          cls: GaussianFourierEmbedding
          kwargs:
            embed_dim: ${shared.pe_dim}
            var: 10.0
        post_process:
          cls: MLP
          kwargs:
            dims: ${eval:'[${shared.embed_dim}]*2'}
            act_fn: elu
    embed_s_f:
      cls: MLP
      kwargs:
        dims: ${eval:'[${shared.embed_dim}]*1'}
        act_fn: elu
    dec:
      cls: KRStack
      kwargs:
        attn:
          cls: MultiheadFastAttention
        num_blks: 6
        skip_every_n: 2
        d_ffn: ${shared.embed_dim}
    head:
      cls: MLP
      kwargs:
        dims: ${eval:'[${shared.embed_dim}]*2+[2]'}
        act_fn: elu
