data:
  grid:
    - start: -2.0
      stop: 2.0
      num: 128
  num_test: 16
  period: 0.2
  loader:
    obs_noise: 0.0
    min_p: 0.05
    max_p: 0.50
    batch_size: 64

infer:
  num_warmup: 500
  num_samples: 1000

train:
  ckpt_path: ckpts/tnpd
  num_batches: 100000
  num_warmup: 10
  learning_rate:
    peak: 1.0e-3
    num_cycles: 1

shared:
  embed_dim: 64

model:
  cls: TNPD
  kwargs:
    embed_s_f:
      cls: LearnableEmbedding
      kwargs:
        map:
          func: 'lambda x: x'
        post_process:
          cls: MLP
          kwargs:
            dims: ${eval:'[${shared.embed_dim}]*4'}
    enc:
      cls: TransformerEncoder
      kwargs:
        attention:
          cls: MultiheadAttention
        num_blks: 6
        d_ffn: ${eval:'2*${shared.embed_dim}'}
    head:
      cls: MLP
      kwargs:
        dims: ${eval:'[${shared.embed_dim}]*2+[2]'}
