defaults:
  - _self_ # use default global values below
  - data: 1d
  - model: sptx_fast
  - kernel: rbf
seed: 42
wandb: True
train_num_steps: 100000
valid_num_steps: 5000
valid_interval: 25000
plot_interval: 100000
lr_peak: 1.0e-3
lr_pct_warmup: 0.3
clip_max_norm: 2.0
