cls: DKR
kwargs:
  num_blks: 3
  num_reps: 2
  embed_s_f:
    cls: MLP
    kwargs:
      dims: [64, 64, 64, 64]
  attn:
    cls: MultiheadAttention
    kwargs:
      proj_out:
        cls: MLP
        kwargs:
          dims: [256, 64]
  head:
    cls: MLP
    kwargs:
      dims: [128, 2]
