cls: TNPDS
kwargs:
  embed_s_f:
    cls: MLP
    kwargs:
      dims: [64, 64, 64, 64]
  enc:
    cls: KRStack
    kwargs:
      num_blks: 6
      num_reps: 1
      blk:
        cls: KRBlock
        kwargs:
          attn:
            cls: MultiheadAttention
            kwargs:
              cls: FastAttention
  head:
    cls: MLP
    kwargs:
      dims: [64, 64, 2]
