cls: TNPKR
kwargs:
  embed_obs_s_f:
    cls: MLP
    kwargs:
      dims: [256, 64]
  bias:
    cls: DistanceBias
    kwargs:
      num_heads: 4
  attn:
    cls: MultiHeadAttention
    kwargs:
      num_heads: 4
  ffn:
    cls: MLP
    kwargs:
      dims: [128, 64]
  head:
    cls: MLP
    kwargs:
      dims: [128, 2]
