cls: TNPKR
kwargs:
  num_blks: 6
  num_reps: 1
  embed_all:
    cls: MLP
    kwargs:
      dims: [256, 128, 64]
      act_fn: gelu
  dist: null
  bias: null
  attn:
    cls: MultiHeadAttention
    kwargs:
      num_heads: 4
      attn:
        cls: DistanceBiasedFastAttention
        kwargs:
          num_ortho_features: 64
          s_rbf_rff:
            cls: RBFRandomFourierFeatures
            kwargs:
              embed_dim: 48
  ffn:
    cls: MLP
    kwargs:
      dims: [256, 64]
      act_fn: gelu
  head:
    cls: MLP
    kwargs:
      dims: [256, 64, 2]
      act_fn: gelu
