cls: TNPDS
kwargs:
  embed_s_f:
    cls: MLP
    kwargs:
      dims: [64, 64, 64, 64]
  enc:
    cls: KRStack
    kwargs:
      attn:
        cls: MultiheadFastAttention
      num_blks: 6
      d_ffn: 128
  head:
    cls: MLP
    kwargs:
      dims: [64, 64, 2]
