_target_: dl4bi.meta_learning.BTNP
num_blks: 6
num_reps: 1
embed_all:
  _target_: dl4bi.mlp.MLP
  dims: [256, 128, 64]
  act_fn:
    _target_: jax.nn.gelu
    _partial_: true
dist: null
bias: null
blk:
  _target_: dl4bi.transformer.KRBlock
  attn:
    _target_: DeepKernelAttention
    num_heads: 1
    proj_qks:
      _target_: dl4bi.mlp.MLP
      dims: [128, 128]
      act_fn:
        _target_: jax.nn.gelu
        _partial_: true
    proj_vs:
      _target_: dl4bi.mlp.MLP
      dims: [128, 64]
      act_fn:
        _target_: jax.nn.gelu
        _partial_: true
  ffn:
    _target_: dl4bi.mlp.MLP
    dims: [256, 64]
    act_fn:
      _target_: jax.nn.gelu
      _partial_: true
head:
  _target_: dl4bi.mlp.MLP
  dims: [256, 64, 3]
  act_fn:
    _target_: jax.nn.gelu
    _partial_: true
output_fn:
  _target_: dl4bi.core.model_output.MultinomialOutput.from_activations
  _partial_: true
